apiVersion: v1
kind: Template
metadata:
  name: my-custom-app-template
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${COLLECTION_NAME}-java
      foo: ${COLLECTION_NAME}
    name: ${COLLECTION_NAME}-java
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      app: ${COLLECTION_NAME}-java
      deploymentconfig: ${COLLECTION_NAME}-java
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${COLLECTION_NAME}-php
      foo: ${COLLECTION_NAME}
    name: ${COLLECTION_NAME}-php
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      app: ${COLLECTION_NAME}-php
      deploymentconfig: ${COLLECTION_NAME}-php
    type: ClusterIP
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    generation: 1
    labels:
      app: ${COLLECTION_NAME}-java
      foo: ${COLLECTION_NAME}
    name: ${COLLECTION_NAME}-java
  spec:
    lookupPolicy:
      local: false
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    generation: 1
    labels:
      app: ${COLLECTION_NAME}-php
      foo: ${COLLECTION_NAME}
    name: ${COLLECTION_NAME}-php
  spec:
    lookupPolicy:
      local: false
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${COLLECTION_NAME}-java
      foo: ${COLLECTION_NAME}
    name: ${COLLECTION_NAME}-java
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: java:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: java-serverhost
      git:
        uri: https://github.com/do288user/DO288-apps
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: redhat-openjdk18-openshift:${{OPENJDK_BUILD}}
        incremental: true
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: ${JAVA_GITHUB_SECRET}
      type: GitHub
    - generic:
        secret: ${JAVA_GENERIC_SECRET}
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${COLLECTION_NAME}-php
      foo: ${COLLECTION_NAME}
    name: ${COLLECTION_NAME}-php
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: php:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: php-helloworld
      git:
        uri: https://github.com/do288user/DO288-apps
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: php:7.2
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: ${PHP_GITHUB_SECRET}
      type: GitHub
    - generic:
        secret: ${PHP_GENERIC_SECRET}
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${COLLECTION_NAME}-java
      foo: ${COLLECTION_NAME}
    name: ${COLLECTION_NAME}-java
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: ${COLLECTION_NAME}-java
      deploymentconfig: ${COLLECTION_NAME}-java
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: ${COLLECTION_NAME}-java
          deploymentconfig: ${COLLECTION_NAME}-java
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/gregab-s2i/java@sha256:93fa1039d0c6c358e07064a4023f1ef3b0877f19e5dc2a3e5eb1413e14bc8e32
          imagePullPolicy: Always
          name: java
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - java
        from:
          kind: ImageStreamTag
          name: java:latest
      type: ImageChange
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${COLLECTION_NAME}-php
      foo: ${COLLECTION_NAME}
    name: ${COLLECTION_NAME}-php
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: ${COLLECTION_NAME}-php
      deploymentconfig: ${COLLECTION_NAME}-php
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: ${COLLECTION_NAME}-php
          deploymentconfig: ${COLLECTION_NAME}-php
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/gregab-s2i/php@sha256:b0f3d3eaf9080beddd86df446752df2a186d81a40090c944bfadb21840e0f698
          imagePullPolicy: Always
          name: php
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - php
        from:
          kind: ImageStreamTag
          name: php:latest
      type: ImageChange
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ${COLLECTION_NAME}-php
      foo: ${COLLECTION_NAME}
    name: ${COLLECTION_NAME}-php
  spec:
    port:
      targetPort: 8080-tcp
    subdomain: ""
    to:
      kind: Service
      name: php
      weight: 100
    wildcardPolicy: None
parameters:
- name: COLLECTION_NAME
  required: true
  description: the value to assign to foo labels of this application
- name: OPENJDK_BUILD
  value: "1.5"
- name: PHP_GITHUB_SECRET
  generate: expression
  from: "[a-zA-Z0-9]{32}"
- name: PHP_GENERIC_SECRET
  generate: expression
  from: "[a-zA-Z0-9]{32}"
- name: JAVA_GITHUB_SECRET
  generate: expression
  from: "[a-zA-Z0-9]{32}"
- name: JAVA_GENERIC_SECRET
  generate: expression
  from: "[a-zA-Z0-9]{32}"
